### ISSUE TITLE
如果项目中引用了YYKit就会冲突了

### ISSUE THREAD

**Issue by renyufei8023** [skx926/KSPhotoBrowser#1]

**Comment by skx926** [comment]
你是以什么方式引用的，如果KSPhotoBrowser和YYKit都是使用Cocopods引用的话应该不会有问题，如果是KSPhotoBrowser是手动添加代码进去的话就不需要再把YYWebImage添加一遍了

**Comment by renyufei8023** [comment]
通过cocoapods，yykit也是通过cocoapods，install的话会安装yycache，yywebiamge，然而这些在yykit里面已经包含了，然后就出现冲突了

**Comment by skx926** [comment]
我新建了一个项目试了一下，没有问题。我看下你的podfile
![image](https://cloud.githubusercontent.com/assets/4225500/21711550/6e58b682-d42a-11e6-86ad-136eb6f3aba6.png)

**Comment by skx926** [comment]
发现问题所在了，这个是比较尴尬了。
现在最理想的解决办法是YYKit的作者能把YYKit改成依赖YYWebImage、YYText、YYModel这几个库，可以给他提建议。
临时的解决办法就是手动把KSPhotoBrowser的代码加进项目。。。

**Comment by skx926** [comment]
摘自YYKit项目介绍：“我希望调用 API 时，有着和调用系统自带 API 一样的体验，所以我并没有为 Category 方法添加前缀。我已经用工具扫描过这个项目中的 API，确保没有对系统 API 产生影响，但即使这样没有前缀的 Category 也可能会带来其他麻烦。因此我不太推荐直接使用 YYKit 这个库，你应该先尝试一下上面那些拆分出来的独立组件。”
