### ISSUE TITLE
为什么要使用YYWebImage

### ISSUE THREAD

**Issue by luo-h** [skx926/KSPhotoBrowser#10]
这样我们就要下载两个image的库了，用SDWebImage不挺好吗

**Comment by skx926** [comment]
个人感觉YYWebImage更加强大，之前也有人提过这方面的需求，希望可以自定义图片缓存库。现在看来这个问题是需要考虑一下了。

**Comment by luo-h** [comment]
恩恩，要是换成SDWebImage就很完美了，哈哈哈

**Comment by skx926** [comment]
SDWebImage以及自定义图片加载类已经在0.1.0版支持，详情请查看项目介绍及Demo.
