### ISSUE TITLE
长按后点击save,崩溃

### ISSUE THREAD

**Issue by spWang** [skx926/KSPhotoBrowser#11]
ios 10.2 ,真机测试

**Comment by skx926** [comment]
是不是没有获取相册的写入权限？

**Comment by skx926** [comment]
崩溃有提示输出吗?

**Comment by spWang** [comment]
因为长按操作可能不同项目会有不同的操作,因此这里我觉得交给子类实现更好一点

然后:
首先非常感谢你的思路以及代码,其次因为我们项目依赖于SDWebImage
这里我对你的代码做了一点改动, 也修复了一些问题,如下:
1.平台改为ios7以上
2.由依赖YYWebImage改为依赖SDWebImage
3.修复一些问题,如有时图片加载完后loading不消失的情况,入参不合理崩溃的情况,图片加载完后model里image为空等
4.增加了部分代理回调,新增sizeToFit属性,表示图片有多大就显示多大
4.对公开API做了容错处理,并给出合理的打印
5.增加了一些注释,禁用了不需有的API,使调用更加规范


再次感谢你的贡献,让我更方便的获取了一个图片浏览器, 也送给有需要的同学
https://github.com/spWang/HCBPhotoBrowser
