### ISSUE TITLE
真机上全屏图片无法拖拽返回

### ISSUE THREAD

**Issue by dandongyan** [skx926/KSPhotoBrowser#14]
在真机上运行时，如果图片铺满整个屏幕，缩放模式返回的情况下，拖拽无法返回。我把scrollView的bounces关掉还是不行

**Comment by dandongyan** [comment]
是图片的高度问题，高度超过屏幕高度的拖拽无法缩放返回

**Comment by skx926** [comment]
好的，感谢反馈

**Comment by dandongyan** [comment]
是否能做个这样的设计：图片往下拉的时候，scrollview不响应，而触发pan手势缩放返回，上拉的时候就触发scrollview的滑动？

**Comment by dandongyan** [comment]
对手势传递这块不熟，改了半天不会，[捂脸]

**Comment by skx926** [comment]
这块处理是比较麻烦一点，我搞好了通知你

**Comment by dandongyan** [comment]
好噢，我现在是加了两个通知来处理，可以缩放返回了，就是返回的的时候会先往原来的位置上面跑，然后再回到原位。 不懂不懂，还是大神你来解决吧， 哈哈

**Comment by skx926** [comment]
问题已经修复
