### ISSUE TITLE
Can We use KSPhotoBrowser on swift projects?

### ISSUE THREAD

**Issue by unittesting0** [skx926/KSPhotoBrowser#2]
It looks awesome,
Can We use KSPhotoBrowser on swift projects?
If yes, how?
Thank you.

**Comment by skx926** [comment]
Normally is will also be available in swift projects. you need to create a bridge header and import KSPhotoBrowser in that file,  then you can use it as a swift class. For detail，you can search in google "how to use oc file in swift" .
