### ISSUE TITLE
iOS10 以下系统不存在CAAnimationDelegate协议

### ISSUE THREAD

**Issue by RITL** [skx926/KSPhotoBrowser#20]

**Comment by skx926** [comment]
这个一直都有啊，发生什么错误了

**Comment by RITL** [comment]
谢谢您的回复，给你看一下，不知道是不是我编译器的问题呢

**Comment by RITL** [comment]
[截图](http://olloonazh.bkt.clouddn.com/%E5%B1%8F%E5%B9%95%E5%BF%AB%E7%85%A7%202017-07-17%20%E4%B8%8B%E5%8D%884.12.30.png)，您用您的编译器看看是不是Xcode自身的问题，我的版本是8.3.3，谢谢啦，游览器真的是很好

**Comment by RITL** [comment]
问题解决了，是这样的楼主，在iOS10之前，存在一个NSObject的CAAnimationDelegate分类，但是iOS10之后就独立出来CAAnimationDelegate这个协议了，谢谢您的第一时间回复

**Comment by skx926** [comment]
也感谢你提出问题，你不说我也不知道有这么一回事，只是记得几年前就在用了😄

**Comment by RITL** [comment]
😄
