### ISSUE TITLE
第一次点进入的图片不会触发代理方法

### ISSUE THREAD

**Issue by ghostlordstar** [skx926/KSPhotoBrowser#21]
谢开源

第一次进入图片时不会触发代理方法，原因就是ViewWillAppear方法里没有调用configItemViews方法
暂时在ViewWillAppear方法中手动调用了代理方法，不知作者有没有更好的解决方法

顺便问一下，为什么不再用SD而改用YY

**Comment by skx926** [comment]
已修复
