### ISSUE TITLE
初始化的KSPhotoItem的时候SourceView有个小问题

### ISSUE THREAD

**Issue by flyOfYW** [skx926/KSPhotoBrowser#22]
我这边是点击个小图，然后就去网络请求，对应的图片资源，不像瀑布流有很多imageView，我只有一个imageView，这个时候，这个SourceView怎么传入啊

**Comment by skx926** [comment]
就传你那个imageView啊

flyOfYW <notifications@github.com>于2017年8月26日 周六下午4:26写道：
