### ISSUE TITLE
这个图片浏览器是否还会更新呢？有一个内存的问题！

### ISSUE THREAD

**Issue by Panshuyan** [skx926/KSPhotoBrowser#25]
1、我从相机中调取本地图片加载到界面，然后使用那个浏览器去点击放大，使用这个KSPhotoBrowser。但是查看内存能涨30多M。然后加载网络图片，点击放大的时候，也是一样，能到40~50M。然后整个项目就达到了130多M，再点就更加高了。这个是不是一个问题？是否有优化的方法？
点击的放大的时候，我的代码是这样的：
UIImageView *imageV = (UIImageView *)tap.view;
    NSMutableArray *items = @[].mutableCopy;
    for (UIImageView *imagev in self.selectedImageArr) {
        KSPhotoItem *item = [KSPhotoItem itemWithSourceView:imagev image:imagev.image];
        [items addObject:item];
    }
    
    KSPhotoBrowser *browser = [KSPhotoBrowser browserWithPhotoItems:items selectedIndex:imageV.tag];
    browser.delegate = self;
    browser.dismissalStyle = KSPhotoBrowserInteractiveDismissalStyleScale;
    browser.backgroundStyle = KSPhotoBrowserBackgroundStyleBlack;
    browser.loadingStyle = KSPhotoBrowserImageLoadingStyleIndeterminate;
    browser.pageindicatorStyle = KSPhotoBrowserPageIndicatorStyleText;
    browser.bounces = NO;
    [browser showFromViewController:_controller];

还请作者指点一二，不胜感激。

当然我也有查询过类似的问题，关于加载高清晰，高像素图片的内存暴涨的问题，如：（http://www.jianshu.com/p/1c9de8dea3ea）但是考虑到您是作者应该更加了解问题所在。盼不吝赐教

**Comment by 308823810** [comment]
我也遇到相同的问题了,解决方法如下 : 
1. 使用这个browser.backgroundStyle = KSPhotoBrowserBackgroundStyleBlur; ,而不是KSPhotoBrowserBackgroundStyleBlurPhoto可以有效的减少内存泄漏

2.加载高清大图时,禁止缓存解压缩后的数据
    [SDImageCache sharedImageCache].config.shouldCacheImagesInMemory = NO;
    [SDImageCache sharedImageCache].config.shouldDecompressImages = NO;

3.收到内存警告时,清除内存
     [[SDImageCache sharedImageCache] setValue:nil forKey:@"memCache"];
