### ISSUE TITLE
Swift 项目中使用会有问题，如下

### ISSUE THREAD

**Issue by angelen10** [skx926/KSPhotoBrowser#29]
尝试使用 Swift，发现会有问题，我看你在 Demo 中点击 cell 的时候做了一个 for 循环，我转换成 Swift 后，在 
```swift
let cell = collectionView.cellForItem(at: IndexPath(row: i, section: 0)) as? JJRHouseCommentListPhotoCell
```
获取当前可见 cell 的时候，有可能返回为 nil（如该 cell 不在屏幕的时候），此时我如果构造 KSPhotoItem，就必须给 cell?.imageView 强制解包（因为你方法中不允许传递 nil），但是给 nil 解包就会报错。
```swift
let item = KSPhotoItem(sourceView: (cell?.imageView)!, imageUrl: url)
```

我也尝试，如果 cell 为空的话，我就不构造 KSPhotoItem，但是这样一来，预览图片的个数就对不上实际图片了，如何解决呢？

**Comment by skx926** [comment]
刚更新到了0.1.5， 支持sourceView可以为空
