### ISSUE TITLE
Consider abstracting the download logic into a protocol

### ISSUE THREAD

**Issue by jyounus** [skx926/KSPhotoBrowser#3]
Hey there,

What do you think of abstracting the YYWebImage implementation to download an image into a protocol? 

In my project, I'm using Kingfisher as my image downloader lib. I would like KSPhotoBrowser to use Kingfisher, because it manages the image cache for me. I don't want YYWebImage to redownload the image when I already have it cached previously.

A protocol which I can conform to would be perfect for me. KSPhotoBrowser could continue using YYWebImage by default, but if I provide my custom implementation, it should use that instead.

I understand you're using YYWebImage for the blur as well, which is perfectly fine for me. I just want to "plug in" my own image downloading/caching implementation for a better user experience.

What do you think?

**Comment by jyounus** [comment]
I would be happy to create a PR if you're okay with my suggestion.

**Comment by skx926** [comment]
I'd like to receive your PR😀

**Comment by jyounus** [comment]
Awesome. I'll start working on this and submit a PR some time later this week! :)

**Comment by skx926** [comment]
Hey there, I have abstracting the image download logic in to a protocol, see the project README.md for detail.
