### ISSUE TITLE
在ipad上直接崩溃

### ISSUE THREAD

**Issue by lichanghong** [skx926/KSPhotoBrowser#30]
Terminating app due to uncaught exception 'NSGenericException', reason: 'Your application has presented a UIAlertController (<UIAlertController: 0x12e846e00>) of style UIAlertControllerStyleActionSheet. The modalPresentationStyle of a UIAlertController with this style is UIModalPresentationPopover. You must provide location information for this popover through the alert controller's popoverPresentationController. You must provide either a sourceView and sourceRect or a barButtonItem.  If this information is not known when you present the alert controller, you may provide it in the UIPopoverPresentationControllerDelegate method -prepareForPopoverPresentation.'

**Comment by skx926** [comment]
这个错误是因为iPad上面用ActionSheet类型的UIAlertController需要设置alertController.popoverPresentationController.sourceView或者sourceRect或者barButtonItem。不过我看了下代码我并没有使用UIAlertController，你看下你是不是用了？

**Comment by lichanghong** [comment]
我也没用UIAlertController，好郁闷啊，就是直接用您的库show的，我现在在找怎么可以兼容iphone和ipad的解决方案。您看能不能兼容一下？网上的库都不兼容

**Comment by skx926** [comment]
我刚在iPad模拟器上跑了，没啥问题啊。你是什么版本的系统？

**Comment by lichanghong** [comment]
我刚在模拟器上跑了也是崩溃，我的mac和iOS都是最新系统

**Comment by skx926** [comment]
直接跑的demo吗？

**Comment by lichanghong** [comment]
我刚试了一下，研究了一下您的demo，您的demo是push方式呈现的，而cocopod上的是present形式呈现的，您别用sege试一下就看到崩溃了

**Comment by skx926** [comment]
那个push是显示图片列表的时候push的，显示KSPhotoBrowser的时候还是用的代码
```objc
- (void)collectionView:(UICollectionView *)collectionView didSelectItemAtIndexPath:(NSIndexPath *)indexPath {
    NSMutableArray *items = @[].mutableCopy;
    for (int i = 0; i < _urls.count; i++) {
        KSPhotoCell *cell = (KSPhotoCell *)[collectionView cellForItemAtIndexPath:[NSIndexPath indexPathForRow:i inSection:0]];
        NSString *url = [_urls[i] stringByReplacingOccurrencesOfString:@"bmiddle" withString:@"large"];
        KSPhotoItem *item = [KSPhotoItem itemWithSourceView:cell.imageView imageUrl:[NSURL URLWithString:url]];
        [items addObject:item];
    }
    KSPhotoBrowser *browser = [KSPhotoBrowser browserWithPhotoItems:items selectedIndex:indexPath.row];
    browser.delegate = self;
    browser.dismissalStyle = _dismissalStyle;
    browser.backgroundStyle = _backgroundStyle;
    browser.loadingStyle = _loadingStyle;
    browser.pageindicatorStyle = _pageindicatorStyle;
    browser.bounces = _bounces;
    [browser showFromViewController:self];
}
```

**Comment by lichanghong** [comment]
哦哦，是我晕了，崩溃不是PhotoBrowser，我是图片在相册多选时候的错误，pod库：TZImagePickerController  感谢帮助^_^
