### ISSUE TITLE
源UIImageView有圆角的问题

### ISSUE THREAD

**Issue by HouWan** [skx926/KSPhotoBrowser#31]
当源UIImageView有圆角时，消失动画就会造成回去时，先方、后圆。

有几个解决办法：
1.在`KSPhotoBrowser`增加圆角属性，消失动画之前，检查这个属性再处理消失动画。
2.在`KSPhotoBrowserDelegate`增加代理方法，消失之前，调用这个方法。
3.在`KSPhotoItem`增加圆角属性，消失动画之前，检查这个属性再处理消失动画。

**Comment by YaoJuan** [comment]
是的，有点难受，我现在也是这个问题

**Comment by skx926** [comment]
有空我搞一下

**Comment by skx926** [comment]
0.1.7 版已经支持圆角的动画显示，欢迎体验和使用
