### ISSUE TITLE
源ImageView和KSPhotoView的问题

### ISSUE THREAD

**Issue by HouWan** [skx926/KSPhotoBrowser#32]
当源`UIImageView`的`contentMode`和`KSPhotoView`的`contentMode`不一致的时候，就会造成回去动画的突兀。

我的办法是在`KSPhotoItem`增加一个属性，属性默认值是`UIViewContentModeScaleAspectFill`，消失动画时检查这个属性，如果不一致，就在动画中改变`KSPhotoView`的`contentMode`

备注：这个问题的由来是超长图问题，长图在显示时，我是按照微博做法，只显示顶部部分长图。
当然，把`KSPhotoItem`的`sourceView`置空也是个解决办法。

**Comment by JLLJHD** [comment]
可以发一份修改后的源码吗？

**Comment by HouWan** [comment]
@JLLJHD 你是遇到什么问题呢？长图？圆角？YYKit？

**Comment by JLLJHD** [comment]
@HouWan 长图和圆角问题
