### ISSUE TITLE
有时在一些机型上查看图片，显示异常是什么原因呢，如图所示

### ISSUE THREAD

**Issue by weak-self** [skx926/KSPhotoBrowser#33]
![img_4359](https://user-images.githubusercontent.com/10719585/37023087-cf81ad28-215f-11e8-90b3-5bdd60b8e2f6.JPG)

**Comment by skx926** [comment]
你说的这种情况我也遇到了，是在iOS8上面吧。这里有解决办法https://www.jianshu.com/p/b2ab0d77f27b

**Comment by weak-self** [comment]
不是这个情况，就是有时在浏览图片时这样，
