### ISSUE TITLE
关于视图消失的问题

### ISSUE THREAD

**Issue by yqy159** [skx926/KSPhotoBrowser#37]
楼主你的demo是for循环创建的imageview。但是我的是用collectionview当我点击第一张图片，然后滑动滑动滑动到第三张，点击dismiss的时候视图会回到第一张，而不是第三张

**Comment by skx926** [comment]
我这也不是创建的imageView，只是一个数组而已，所以你需要拿到collectionView里的imageView赋给相应的item

yqy159 <notifications@github.com>于2018年5月2日周三 下午12:48写道：
