### ISSUE TITLE
KSPhotoBrowser swipe to next photo delegate

### ISSUE THREAD

**Issue by jyounus** [skx926/KSPhotoBrowser#4]
The demo app has a number of static views on screen. However my app displays profile images of a user which basically takes the top 40% of the screen. The images are inside of a paginated UIScrollView. 

It would be great if I could listen to index changes, so that every time the user swipes left/right when the KSPhotoBrowser is displayed, I can update the scroll position of my paginated UIScrollView.

**Comment by skx926** [comment]
That's reasonable, I will add that delegate soon.

**Comment by skx926** [comment]
Index change delegate has been added in 0.0.4
