### ISSUE TITLE
和SSZipArchive压缩库冲突 同时引入提示'YYWebImage.h' file not found

### ISSUE THREAD

**Issue by hjqiaho** [skx926/KSPhotoBrowser#47]
pod 'KSPhotoBrowser'
pod 'SSZipArchive'

/Users/   --- /Pods/KSPhotoBrowser/KSPhotoBrowser/KSYYImageManager.m:14:9: 'YYWebImage.h' file not found

**Comment by skx926** [comment]
我刚试了一下没有问题，新版已经把默认的图片库换成SDWebImage了，不会包含KSYYImageManager这个文件了，我估计你这是缓存的问题，删掉重新安装一下
