### ISSUE TITLE
If you use collectionView how to implement it?

### ISSUE THREAD

**Issue by fuchenxi** [skx926/KSPhotoBrowser#5]

**Comment by skx926** [comment]
```objc
- (void)collectionView:(UICollectionView *)collectionView didSelectItemAtIndexPath:(NSIndexPath *)indexPath {
    UICollectionViewCell *cell = [collectionView cellForItemAtIndexPath:indexPath];
    // Get the source imageView from your cell
}

```

**Comment by skx926** [comment]
```objc
- (void)collectionView:(UICollectionView *)collectionView didSelectItemAtIndexPath:(NSIndexPath *)indexPath {
    for (int i = 0; i < _models.count; i++) {
        UICollectionViewCell *cell = [collectionView cellForItemAtIndexPath:[NSIndexPath indexPathForItem:i inSection:0]];
        // Get the imageView from your cell and create KSPhotoItem
    }
    // Show KSPhotoBrowser
}
```
Because collectionView's cell is reusable, if your cell are all showing in screen, this method is fine, otherwise some of them will get the wrong dismissal animation.

**Comment by fuchenxi** [comment]
这个问题刚才已经解决了, 我现在的需求是顶部一个展示商品图片的collectionView, 宽度为屏幕的宽, 当我点击第一个item, 在KSPhotoBrowser 手动滑到第三个或者其他, 当我dismiss的时候, 我如何和我自己的item进行对应? 并且item的显示隐藏如何对应?

**Comment by skx926** [comment]
其实就跟我上面说的一样，如果你只有几个item并且都已经显示在屏幕上，只需要在创建KSPhotoItem的时候传入正确的sourceView就可以。如果是有一些item没有显示的屏幕上。在photo browser里滑动到的时候消失动画就会有问题，因为没有对应的sourceView。

**Comment by skx926** [comment]
对于没有显示出来的item我后面会修改一下，让它有一个不一样的消失动画

**Comment by fuchenxi** [comment]
目前我可以在哪里手动更改一下?

**Comment by fuchenxi** [comment]
刚开始看, 还不是很了解

**Comment by skx926** [comment]
572行- (void)showDismissalAnimation; 在这里你可以判断一下sourceRect是不是(0,0,0,0)，如果是就说明sourceView没有显示在屏幕上，你可以给它一个固定的rect，比如屏幕的中间。

**Comment by fuchenxi** [comment]
谢谢, 之前用另一个PhotoBrowser就是这样解决的, 我会关注您的更新的, 加油

**Comment by fuchenxi** [comment]
直接写死dismiss的时候x值会不正确, const CGFloat kKSPhotoViewPadding = 10; 控制一下这个值就习惯了, 朋友们谁需要就看一下

**Comment by skx926** [comment]
x值会不正确？什么意思

**Comment by menicor** [comment]
创建KSPhotoItem的时候必须传sourceView  ，但是没显示出来的collectionCell怎么办 ，这个时候也得不到未显示出来的cell

**Comment by skx926** [comment]
未显示出来的可以让它默认从屏幕中间消失

**Comment by menicor** [comment]
怎么让从屏幕中间消失呢 ，是学的swift ，oc的看的不太懂 ，求解

**Comment by skx926** [comment]
我五一假期改一下吧，到时候你更新一下就行了

**Comment by menicor** [comment]
这个我想办法实现了 ，能不能根据图片的本地路径去加载显示大图啊 ，外部构建KSPhotoItem的时候把原图传进去 ，浏览本地相册的时候图片很多 ，导致内存溢出

**Comment by skx926** [comment]
嗯，可以的

**Comment by menicor** [comment]
额 ，那传原图进去导致内存溢出怎么解决

**Comment by skx926** [comment]
就不要传原图了，那么多图加载到内存本身就不合理

**Comment by menicor** [comment]
查看大图不使用原图那使用什么 ，或者说如何实现不要一次性把原图取出来用来构建KSPhotoItem ，实现滑动一张读取一张

**Comment by skx926** [comment]
就跟URL一样，传你从相册里读取的资源路径或者对象，当然KSPhotoBrowser现在还没支持。
