### ISSUE TITLE
升级0.2.5,sdwebimage5.0.1之后KSSDImageManager内报错

### ISSUE THREAD

**Issue by jabirKuo** [skx926/KSPhotoBrowser#56]
![WechatIMG2](https://user-images.githubusercontent.com/10990980/56078808-d1005300-5e1e-11e9-9fde-94735ef8443e.png)
![WechatIMG3](https://user-images.githubusercontent.com/10990980/56078809-d2ca1680-5e1e-11e9-813a-b960144577a6.png)
![WechatIMG4](https://user-images.githubusercontent.com/10990980/56078811-d65d9d80-5e1e-11e9-92f5-ae8b918006aa.png)

**Comment by skx926** [comment]
0.3.0已支持SD5.0
