### ISSUE TITLE
图片保存本地之后加个提示呗，本来想自己加的，又不想改您的源码

### ISSUE THREAD

**Issue by kzq5** [skx926/KSPhotoBrowser#57]

**Comment by skx926** [comment]
我刚试了一下，UIActivityViewController的回调只会告诉点击了哪个Item，并不会返回图片有没有保存成功，不论是成功还是失败返回结果都是一样的。所以我这里直接加提示不完美。
你如果一定要提示的话可以实现长按的delegate然后自己调起UIActivityViewController或者直接把图片写入相册然后再根据结果进行提示
