### ISSUE TITLE
请处理下SDWebImage版本号的问题

### ISSUE THREAD

**Issue by fuhailong** [skx926/KSPhotoBrowser#58]
[!] CocoaPods could not find compatible versions for pod "SDWebImage":
  In snapshot (Podfile.lock):
    SDWebImage (= 5.0.1, >= 5.0.0)

  In Podfile:
    KSPhotoBrowser (~> 0.2.5) was resolved to 0.2.5, which depends on
      SDWebImage (~> 4.0)

    SDCycleScrollView (~> 1.80) was resolved to 1.80, which depends on
      SDWebImage (>= 5.0.0)

有SDWebImage版本号冲突
最好不添加这种依赖  然后让使用者去选择

**Comment by skx926** [comment]
你是升级到5.0了吗

**Comment by skx926** [comment]
0.3.0已支持SD5.0

**Comment by fuhailong** [comment]
谢谢
