### ISSUE TITLE
无法通过delegate方法的item取出image

### ISSUE THREAD

**Issue by zhangyandong** [skx926/KSPhotoBrowser#6]
感谢作者无私开源
但是使用时发现通过KSPhotoBrowserDelegate方法无法拿到通过url加装完毕后的image，KSPhotoItem的image属性未在图片加装完毕后赋值

**Comment by skx926** [comment]
这个image是用来在初始化item的时候直接传image进去的。你现在是什么样的使用场景才需要下载到的图片呢？

**Comment by zhangyandong** [comment]
比如长按图片之后处理一些自己的业务逻辑，改了一点源码后，想了一下和作者整体的设计有关，需要改的地方还不少

**Comment by skx926** [comment]
KSPhotoBrowser (0.1.7)已经支持长按手势自定义，可以通过KSPhotoBrowser的`- (UIImage *)imageForItem:(KSPhotoItem *)item;`和`
- (UIImage *)imageAtIndex:(NSUInteger)index;`来获取图片
