### ISSUE TITLE
ios14有bug 已经不能用了

### ISSUE THREAD

**Issue by zhouxiaowei** [skx926/KSPhotoBrowser#66]
ios14有bug 已经不能用了 点开就是纯色背景

**Comment by h386926074** [comment]
也出现这个问题了

**Comment by h386926074** [comment]
是这的问题
YYAnimatedImageView.m

(void)displayLayer:(CALayer *)layer {
if (_curFrame) {
layer.contents = (__bridge id)_curFrame.CGImage;
} else {
// If we have no animation frames, call super implementation. iOS 14+ UIImageView use this delegate method for rendering.
if ([UIImageView instancesRespondToSelector:@selector(displayLayer:)]) {
[super displayLayer:layer];
}
}
}

**Comment by HouWan** [comment]
建议改成`SDWebImage`，它里面有替代品，比如`SDAnimatedImageView`

**Comment by ahuinee** [comment]
升级SDWebImage到最新版本即可修复次问题
引用： https://github.com/SDWebImage/SDWebImage/pull/3046

**Comment by skx926** [comment]
鉴于YYWebImage已经没人维护，已经将YYWebImage移除，只保留SDWebImage
