### ISSUE TITLE
Unable to find a pod with name, author, summary, or description matching `KSPhotoBrowser`

### ISSUE THREAD

**Issue by jimisfans** [skx926/KSPhotoBrowser#7]
Unable to find a pod with name, author, summary, or description matching `KSPhotoBrowser`

gem
version:2.6.7
source: https://gems.ruby-china.org/

cocoapods
version:1.2

**Comment by jimisfans** [comment]
pod 'KSPhotoBrowser', :git => 'https://github.com/skx926/KSPhotoBrowser'

**Comment by skx926** [comment]
You can run commands below line by line and then retry:
```bash
pod setup
rm ~/Library/Caches/CocoaPods/search_index.json
```
![screen shot 2017-03-16 at 10 37 43](https://cloud.githubusercontent.com/assets/4225500/23979464/a1fca83c-0a34-11e7-85e7-7a24d7f7a433.png)
