### ISSUE TITLE
iOS 14.4显示不出照片

### ISSUE THREAD

**Issue by PengJiang520** [skx926/KSPhotoBrowser#71]
NSArray *urls = @[_exchangesModel.guideImg];
    NSMutableArray *imageArr = [NSMutableArray array];
    
    for (int i = 0; i < urls.count; i++) {
        // Get the large image url
        NSString *url = urls[i];

      //  KSPhotoItem *item = [KSPhotoItem itemWithSourceView:[[UIImageView alloc]initWithImage:[UIImage imageNamed:@"o_empty_image"]] imageUrl:[NSURL URLWithString:url]];
        
        
        
        KSPhotoItem *item = [KSPhotoItem itemWithSourceView:[UIImageView alloc] image:[UIImage imageNamed:@"o_empty_image"]];
        
        [imageArr addObject:item];
    }
    KSPhotoBrowser *browser = [KSPhotoBrowser browserWithPhotoItems:imageArr selectedIndex:0];
    browser.dismissalStyle = KSPhotoBrowserInteractiveDismissalStyleScale;
    browser.backgroundStyle = KSPhotoBrowserBackgroundStyleBlur;
    [browser showFromViewController:self];

**Comment by skx926** [comment]
升级SD到最新看看哈
